Repository QAZIMAAZARSHAD/Movie-Streaming-Website, pull requests merged in 2021-06, with the labels that each got.

#87 Fixed footer overlapping bug
  static/style.css
Labels: LGMSOC21, 🟩 Level1

#16 login page redesign
  login.html
Labels: LGMSOC21, 🟧 Level3

#74 Added custom scrollbar to all the pages
  action.html
  comedy.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  popular.html
  static/style.css
  suspense.html
  war.html
Labels: LGMSOC21, 🟨 Level2

#97 Changing title of the Website
  index.html
Labels: LGMSOC21, 🟩 Level1

#61 designed Kids page
  Images/BalGanesh.jpg
  Images/Hanuman.jpg
  Images/Mouse_detective.jpg
  Images/Phineas.jpg
  Images/bolt.jpg
  Images/bugs_life.jpg
  Images/cars.jpg
  Images/cinderalla.jpg
  Images/doraemon.jpg
  Images/doraemon_cover.jpg
  Images/frozen.jpg
  Images/jungle-book.jpg
  Images/lion_king.jpg
  Images/little_einsteins.jpg
  Images/mermaid.png
  Images/mickey_mouse cover.png
  Images/mickey_mouse.jpg
  Images/nemo.jpg
  Images/pinocchio.jpg
  Images/shinChan.jpg
  Images/shinchan_cover.jpg
  Images/snow_white.jpg
  Images/sofia.jpg
  Images/spider_man_cover.png
  Images/tangled.jpg
  Images/toy_story.jpg
  index.html
  kids.html
Labels: LGMSOC21, 🟨 Level2

#102 Contact Page
  contactus.html
  index.html
  static/style.css
Labels: LGMSOC21, 🟧 Level3

#105 Issue #3 | Applied zoom hover effect | Apply creative hover effect on all images
  static/style.css
Labels: LGMSOC21, 🟩 Level1

#107 #96 Contributors section added in the README file
  README.md
Labels: LGMSOC21, 🟩 Level1

#111 Genre Navigation bar improved
  action.html
  comedy.html
  crime.html
  documentary.html
  drama.html
  fantasy.html
  horror.html
  index.html
  popular.html
  static/style.css
  suspense.html
  war.html
Labels: LGMSOC21, 🟩 Level1

#116 Footer
  index.html
  static/style.css
Labels: LGMSOC21, 🟨 Level2

#128 made the quiz interest page
  js/questions.js
  js/script.js
  login.html
  quiz.html
  quizstyle.css
Labels: LGMSOC21, 🟥 Level4

#129 slider updated
  index.html
  static/style.css
Labels: LGMSOC21, 🟨 Level2

#132 added password constraints
  login.html
Labels: LGMSOC21, 🟨 Level2

#135 Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#143 change in welcome line
  index.html
  static/style.css
Labels: LGMSOC21, 🟩 Level1

#139 Added footer to all the pages
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  popular.html
  quiz.html
  static/style.css
  suspense.html
  war.html
Labels: LGMSOC21, 🟨 Level2

#153 Add Logo in Logo folder
  Images/Logo/Apna Theater (1).png
  Images/Logo/UpdatedLogo.png
Labels: LGMSOC21, 🟪 Level0

#151 Fixed #4 : make a creative logo for the website
  Images/logo/Apna theatre.png
Labels: LGMSOC21, 🟪 Level0

#155 Added logo fixed issue #4
  Images/Logo/Apna Theatre-Nikhita28.png
  Images/Logo/Apna theatre (Nikhita28).png
Labels: LGMSOC21, 🟪 Level0

#154 Logo added
  Images/Logo/logo.gif
  Images/logo.gif
  index.html
Labels: LGMSOC21, 🟪 Level0

#148 TV page (popular hindi tv serials for our audience)
  Images/anupama2.jpg
  Images/big.jpg
  Images/crime.jpg
  Images/fear.jpg
  Images/gum hai kisi.jpg
  Images/indianidol.jpg
  Images/kbc.jpg
  Images/shaurya.jpg
  Images/tmkoc.jpg
  Images/yeh rishta.jpg
  index.html
  tv.html
Labels: LGMSOC21, 🟨 Level2

#138 designed web-series page
  Images/Asur_cover.png
  Images/family_man.jpg
  Images/family_man_cover.jpeg
  Images/family_man_cover.jpg
  Images/mirzapur_cover.jpg
  Images/sacred_games_cover.jpg
  Images/scam_cover.jpg
  Images/stranger_things.jpg
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  popular.html
  static/style.css
  suspense.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟨 Level2

#158 Cursor added while hovering on the movies
  index.html
  static/style.css
Labels: LGMSOC21, 🟪 Level0

#165 Added logo for website.
  Images/Logo/web_logo-01.png
Labels: LGMSOC21, 🟪 Level0

#169 Added Email verification
  login.html
  signup.html
Labels: LGMSOC21, 🟥 Level4

#187 Cursor Added To Kids, TV And WebSeries Page
  kids.html
  tv.html
  web-series.html
Labels: LGMSOC21, 🟪 Level0

#189 Apna Theatre(BeginnerCoder21)
  Images/Logo/TheaterLogo.png
Labels: LGMSOC21, 🟪 Level0

#193 Added Movie Cards
  Images/1917.jpg
  Images/99.jpg
  Images/arrow.jpg
  Images/big.jpg
  Images/chhal.jpg
  Images/college.jpg
  Images/dil.jpg
  Images/django.jpg
  Images/dunkirk.jpg
  Images/edu.jpg
  Images/family.jpg
  Images/flash.jpg
  Images/friends.jpg
  Images/game.jpg
  Images/gravity.jpg
  Images/harry.jpg
  Images/hunger.jpg
  Images/hustle.jpg
  Images/inter.jpg
  Images/it.jpg
  Images/joker.jpg
  Images/kgf.jpg
  Images/kong.jpg
  Images/kung.jpg
  Images/lord.jpg
  Images/luci.jpg
  Images/mohabat.jpg
  Images/money.jpg
  Images/mortal.jpg
  Images/peaky.jpg
  Images/rick.jpg
  Images/sachin.jpg
  Images/social.jpg
  Images/special.jpg
  Images/star.jpg
  Images/stranger.jpg
  Images/tenet.jpg
  Images/ter.jpg
  Images/tom.jpg
  Images/upsc.jpg
  Images/veronica.jpg
  Images/vikings.jpg
  Images/walk.jpg
  Images/wanda.jpg
  Images/war.jpg
  Images/zindagi.jpg
  action.html
  comedy.html
  crime.html
  documentary.html
  drama.html
  fantasy.html
  horror.html
  index.html
  popular.html
  suspense.html
  war.html
Labels: LGMSOC21, 🟩 Level1

#188 All Buttons Linked Correctly
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  fantasy.html
  horror.html
  kids.html
  popular.html
  romance.html
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟩 Level1

#195 Enhance Tagline by Hovering Effects
  static/style.css
Labels: LGMSOC21, 🟪 Level0

#205 Hover effect on images and text in kids.html and web-series.html
  kids.html
  web-series.html
Labels: LGMSOC21, 🟨 Level2

#218 Update README.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#207 Made a Whole website completely Responsive
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  popular.html
  romance.html
  static/style.css
  suspense.html
  tv.html
  war.html
  web-series.html
  webStyle.css
Labels: LGMSOC21, 🟥 Level4

#211 hover effect on footer
  static/style.css
Labels: LGMSOC21, 🟩 Level1

#236 add logo in about section
  Images/Logo/logo1.png
  README.md
Labels: LGMSOC21, 🟪 Level0

#246 favicon added
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  login.html
  popular.html
  quiz.html
  romance.html
  signup.html
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟪 Level0

#255 Rishika
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  popular.html
  romance.html
  static/style.css
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟩 Level1

#265 Changed Footer Copyright Year
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  horror.html
  index.html
  kids.html
  popular.html
  romance.html
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟩 Level1

#305 Fixed overlapping posters on homepage
  static/style.css
Labels: LGMSOC21, 🟪 Level0

#309 landpage fixed
  Images/land.jpg
  home.html
  index.html
  landpage.css
Labels: LGMSOC21, 🟩 Level1

#310 Scroll to top button
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  home.html
  horror.html
  kids.html
  popular.html
  romance.html
  signup.html
  static/style.css
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟩 Level1

#313 Rishika1
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  home.html
  horror.html
  index.html
  kids.html
  popular.html
  romance.html
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟪 Level0

#319 signin and signup buttons corrected
  login.html
  signup.html
Labels: LGMSOC21, 🟪 Level0

#322 Logo and Home tab redirecting to home page
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  home.html
  horror.html
  kids.html
  movies.html
  popular.html
  romance.html
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟪 Level0

#338 Added score card in readme
  README.md
Labels: LGMSOC21, 🟪 Level0

#349 Issue #335
  action.html
  comedy.html
  contactus.html
  crime.html
  documentary.html
  drama.html
  dummy.html
  fantasy.html
  home.html
  horror.html
  kids.html
  popular.html
  romance.html
  static/style.css
  suspense.html
  tv.html
  war.html
  web-series.html
Labels: LGMSOC21, 🟪 Level0

#360 Added mailto: link
  login.html
  signup.html
Labels: LGMSOC21, 🟪 Level0
